app = "financialappbackend"
primary_region = "sjc"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "./Dockerfile"

[deploy]

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[resources]
  cpu = "shared-cpu-1x"  # smallest shared CPU
  memory = "256mb"       # smallest memory size allowed by Fly.io

[scale]
  min_machines = 0       # scale down to zero instances when idle
  max_machines = 1       # allow only one instance running

